gh-1: Delete hello function (#11)
After we added a proper crate member with an associated proper test, the
hello function for a smoke test is no longer relevant.

Also it fixes irrelevant linter errors:

```plain
error: this function's return value is unnecessary
 --> tests/smoke.rs:4:1
  |
4 | / fn test_import() -> Result<(), Box<dyn std::error::Error>> {
5 | |     assert!(hello());
6 | |     Ok(())
7 | | }
  | |_^
  |
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_wraps
  = note: `-D clippy::unnecessary-wraps` implied by `-D warnings`
  = help: to override `-D warnings` add `#[allow(clippy::unnecessary_wraps)]`
help: remove the return type...
  |
4 | fn test_import() -> Result<(), Box<dyn std::error::Error>> {
  |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
help: ...and then remove returned values
  |
6 -     Ok(())
6 +     
  |
```