Fix unused imports error, again
```plain
error: unused imports: `IdentifierName`, `PrivateIdentifier`
  --> src/lib.rs:13:92
   |
13 | ...t, IdentifierName, InputElementDiv, InputElementHashbangOrRegExp, InputElementRegExp, InputElementRegExpOrTemplateTail, InputElementTemplateTail, LineTerminator, PrivateIdentifier, R...
   |       ^^^^^^^^^^^^^^                                                                                                                                                 ^^^^^^^^^^^^^^^^^
   |
```