Fix clippy::enum_variant_names
```plain
error: all variants have the same prefix: `InputElement`
   --> src/lib.rs:738:1
    |
738 | / enum PackedToken {
739 | |     InputElementDiv(InputElementDiv),
740 | |     InputElementHashbangOrRegExp(InputElementHashbangOrRegExp),
741 | |     InputElementRegExp(InputElementRegExp),
742 | |     InputElementRegExpOrTemplateTail(InputElementRegExpOrTemplateTail),
743 | | }
    | |_^
    |
    = help: remove the prefixes and use full paths to the variants instead of glob imports
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#enum_variant_names
    = note: `-D clippy::enum-variant-names` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::enum_variant_names)]`
```