Add missing Eq and PartialEq trait
Example specimen:

```plain
error[E0277]: the trait bound `lexical_grammar::LineTerminator: Eq` is not satisfied
  --> src/lib.rs:65:20
   |
59 | #[derive(Debug, Eq, PartialEq)]
   |                 -- in this derive macro expansion
...
65 |     LineTerminator(LineTerminator),
   |                    ^^^^^^^^^^^^^^ the trait `Eq` is not implemented for `lexical_grammar::LineTerminator`
   |
note: required by a bound in `AssertParamIsEq`
  --> /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/cmp.rs:360:1
   = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `lexical_grammar::LineTerminator` with `#[derive(Eq)]`
  --> src/lexical_grammar.rs:95:1
   |
95 + #[derive(Eq)]
96 | pub struct LineTerminator;
   |
```

```plain
error[E0369]: binary operation `==` cannot be applied to type `lexical_grammar::WhiteSpace`
  --> src/lib.rs:68:16
   |
59 | #[derive(Debug, Eq, PartialEq)]
   |                     --------- in this derive macro expansion
...
68 |     WhiteSpace(WhiteSpace),
   |                ^^^^^^^^^^
   |
note: an implementation of `PartialEq` might be missing for `lexical_grammar::WhiteSpace`
  --> src/lexical_grammar.rs:91:1
   |
91 | pub struct WhiteSpace;
   | ^^^^^^^^^^^^^^^^^^^^^ must implement `PartialEq`
   = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `lexical_grammar::WhiteSpace` with `#[derive(PartialEq)]`
  --> src/lexical_grammar.rs:91:1
   |
91 + #[derive(PartialEq)]
92 | pub struct WhiteSpace;
   |
```