Fix clippy::missing-errors-doc
```plain
error: docs for function returning `Result` missing `# Errors` section
  --> src/lib.rs:36:1
   |
36 | pub fn get_next_token(input: &str) -> Result<(Token, &str), String> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_errors_doc
   = note: `-D clippy::missing-errors-doc` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::missing_errors_doc)]`
```