Fix clippy::missing-panics-doc
```plain
error: docs for function which may panic missing `# Panics` section
  --> src/lib.rs:30:1
   |
30 | pub fn get_next_token(input: &str) -> Result<(Token, &str), String> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: first possible panic found here
  --> src/lib.rs:34:25
   |
34 |             let token = tokens.nth_back(0).unwrap();
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_panics_doc
   = note: `-D clippy::missing-panics-doc` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::missing_panics_doc)]`
```