Fix clippy::missing-const-for-fn
```plain
error: this could be a `const fn`
  --> src/lib.rs:85:1
   |
85 | / fn extract_token(symbol_tree: InputElementDiv) -> Token {
86 | |     match symbol_tree {
87 | |         InputElementDiv::DecimalDigit(value) => Token::NumericLiteral(value.digit.value),
88 | |         InputElementDiv::WhiteSpace(_) => Token::WhiteSpace,
89 | |     }
90 | | }
   | |_^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_fn
   = note: `-D clippy::missing-const-for-fn` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::missing_const_for_fn)]`
```